#! /bin/sh

# startup
~/.local/bin/monitorSetup.sh
sxhkd &
pgrep bspswallow || bspswallow &
udiskie & # for some reason this doesn't launch in .xinitrc

# bspwm
bspc config border_width         1
bspc config window_gap          12
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

# colors
bspc config focused_border_color \#FFFFFF
#source ~/.cache/wal/colors.sh
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
#bspc config presel_feedback_color $color4

# tiling rules
bspc rule -a Zathura state=tiled
bspc rule -a feh state=floating
bspc rule -a zoom state=floating

# bar
$HOME/.config/polybar/launch.sh &
